### ISSUE TITLE
removeAt(index)

### ISSUE THREAD

**Issue by masalha-alaa** [bluefireteam/ordered_set#28]
Great package, but if there's an `elementAt` method, why isn't there a `removeAt` method? Currently to imitate that I do `mySet.remove(mySet.elementAt(index))`.

Is it possible to add a `removeAt()` method that accepts an index and removes the item at that index?

**Comment by spydon** [comment]
The `elementAt` comes from Dart's `IterableMixin`, hence why we haven't added any `removeAt` method.
https://api.dart.dev/stable/2.7.2/dart-collection/IterableMixin-class.html

It wouldn't hurt to have that method though, so if you want to add it, feel free to put up a PR. :)

**Comment by masalha-alaa** [comment]
Got it, thanks. I have only about 10 days experience in Flutter & Dart, so I'll leave it to someone else 😄
For now I'll be using `mySet.remove(mySet.elementAt(index))`
