### ISSUE TITLE
refactor: query() should return an Iterable, not List

### ISSUE THREAD

**Issue by filiph** [bluefireteam/ordered_set#31]
As discussed [on Discord](https://discord.com/channels/509714518008528896/1255127093310918686/1255170714709921812), returning a `List` from [`QueryableOrderedSet.query()`](https://github.com/bluefireteam/ordered_set/blob/main/lib/queryable_ordered_set.dart#L73C11-L73C16) leads to bugs. The developer assumes they own the returned list, then modify it in place (with `removeWhere()`, for example) to avoid creating yet another iterable. Unbeknownst to the, they're modifying the internal cache of the `QueryableOrderedSet`.

We agreed to make the breaking change of returning `Iterable<C>` on [this line](https://github.com/bluefireteam/ordered_set/blob/main/lib/queryable_ordered_set.dart#L73). Nothing other than that function needs to change, as `List` is already an `Iterable`, so we're only exposing the same data structure as a different static type.

This is breaking because people can have the results of `query()` assigned to typed variables, such as `List<Entity> blah = world.query<Entity>();`. But that's easy to fix.

If anyone is actually _using_ the return of `query()` as a modifiable `List` (as in, they modify it), then that's likely a bug. The change will uncover the bug, so all's good.

The only other valid thing that this could change is code such as `var something = blah[index]`, or `for (int i = 0; i < blah.length; i++) doThing(blah[i]);`. These are probably rare but valid.

cc @spydon

**Comment by spydon** [comment]
Sounds good, do you want to open a PR with the change? :)
